## Note : this is the new way to apply wallpapers
wallpaper {
    monitor = DP-1
    path = $HOME/.config/choppydev.mk1/wallpapers/wallpaper1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/.config/choppydev.mk1/wallpapers/wallpaper1.jpg
    fit_mode = cover
}
