## Note : this is the new way to apply wallpapers
wallpaper {
    monitor = DP-1
    path = ~/Images/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Images/wallpaper.jpg
    fit_mode = cover
}
