###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, space, exec, rofi -show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, F, fullscreenstate, 3
bind = $mainMod, L, exec, hyprlock
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-10]
bind = $mainMod, code:10, split-workspace, 1
bind = $mainMod, code:11, split-workspace, 2
bind = $mainMod, code:12, split-workspace, 3
bind = $mainMod, code:13, split-workspace, 4
bind = $mainMod, code:14, split-workspace, 5
bind = $mainMod, code:15, split-workspace, 6
bind = $mainMod, code:16, split-workspace, 7
bind = $mainMod, code:17, split-workspace, 8
bind = $mainMod, code:18, split-workspace, 9
bind = $mainMod, code:19, split-workspace, 10

bind = $mainMod SHIFT, code:10, split-movetoworkspace, 1
bind = $mainMod SHIFT, code:11, split-movetoworkspace, 2
bind = $mainMod SHIFT, code:12, split-movetoworkspace, 3
bind = $mainMod SHIFT, code:13, split-movetoworkspace, 4
bind = $mainMod SHIFT, code:14, split-movetoworkspace, 5
bind = $mainMod SHIFT, code:15, split-movetoworkspace, 6
bind = $mainMod SHIFT, code:16, split-movetoworkspace, 7
bind = $mainMod SHIFT, code:17, split-movetoworkspace, 8
bind = $mainMod SHIFT, code:18, split-movetoworkspace, 9
bind = $mainMod SHIFT, code:19, split-movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, m+1
bind = $mainMod, mouse_up, workspace, m-1
bind = $mainMod CTRL, right, workspace, m+1
bind = $mainMod CTRL , left, workspace, m-1

# Swaping windows
bind = $mainMod SHIFT, left, swapwindow, l
bind = $mainMod SHIFT, right, swapwindow, r
bind = $mainMod SHIFT, up, swapwindow, u
bind = $mainMod SHIFT, down, swapwindow, d

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && notify-send "Volume" "Increasing volume to $(wpctl get-volume @DEFAULT_SINK@ | awk '{print int($2*100)}')%"
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send "Volume" "Descreasing volume to $(wpctl get-volume @DEFAULT_SINK@ | awk '{print int($2*100)}')%"
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

#Screenshots
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = SHIFT, Print, exec, grim - | wl-copy
bind = CTRL, Print, exec, grim -g "$(slurp)" ~/Images/screenshot-$(date +%F-%T).png