plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1

        # set this to 1 for gnome-like workspace switching
        link_monitors = 0

        # if you want a different monitor order
        monitor_priority = eDP-1, HMDI-A-1

        # you can also set max workspaces per monitor
        max_workspaces = eDP-1, 5
        max_workspaces = HMDI-A-1, 5
        # link_monitors = 1
    }
}